

server:
  port: 8092

spring:
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:tcp://localhost/~/sinchon;MODE=MYSQL
      username: sa
      password:

      connection-timeout: 20000
      minimum-idle: 5
      maximum-pool-size: 5
      validation-timeout: 300000
      max-lifetime: 1200000



  mail:
    host: smtp.gmail.com
    port: 587
    username: watersun326@gmail.com
    password: kqzmoqjhpgdubvgq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  sql:
    init:
      encoding: utf-8

  h2:
    console:
      enabled: true
      path: /con




  messages:
    basename: errors,messages

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
#  configuration:
#    lazy-loading-enabled: true
#    aggressive-lazy-loading: false
#logging:
#  level:
#    org:
#      apache:
#        coyote:
#          http11: debug
#    map-underscore-to-camel-case: true


