server:
  port: 8092

spring:
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:tcp://localhost/~/sinchon
      username: sa
      password:


mybatis:
  mapper-locations: mappers/**/*.xml
